import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import {createGateway,ROOT} from '../../server/gateway.mjs';
import {browserLogin,authenticate,client,password} from '../auth-helper.mjs';

test('maximize focuses the target, persists restore bounds and opens a private deep link once',{timeout:35000},async()=>{
 const runtime=await mkdtemp(ROOT+'.test-desktop-max-'),g=await createGateway({port:0,runtime}),browser=await chromium.launch({headless:true,chromiumSandbox:true}),page=await browser.newPage({viewport:{width:1300,height:900},reducedMotion:'reduce'});page.setDefaultTimeout(4000);const button=name=>page.getByRole('button',{name,exact:true});
 try{await browserLogin(page,g.origin,runtime);await button('Open Parcels').click();const parcels=page.locator('[data-app="parcels"]'),bounds=await parcels.boundingBox();await button('Navigation').click();await page.locator('.quick-nav').getByRole('button',{name:/Keepsakes/}).click();await expect(parcels).not.toHaveClass(/focused/);await button('Maximize Parcels').focus();await page.keyboard.press('Enter');await expect(parcels).toHaveClass(/focused/);const link=page.url();await expect(page).toHaveURL(/view=maximized/);
  await page.reload();await expect(button('Restore size Parcels')).toBeVisible();await button('Restore size Parcels').click();const restored=await parcels.boundingBox();assert.deepEqual(restored,bounds);
  await button('Navigation').click();await button('Sign out').click();await page.goto(link);await expect(page.getByRole('heading',{name:'login',exact:true})).toBeVisible();let opens=0;page.on('request',r=>{if(r.url()===g.origin+'/api/windows'&&r.method()==='POST')opens++;});await page.getByLabel('username',{exact:true}).fill('admin');await page.getByLabel('password',{exact:true}).fill(password);await button('Enter →').click();await expect(button('Restore size Parcels')).toBeVisible();await expect(parcels).toHaveCount(1);assert.ok(opens<=1);assert.equal(page.url(),link);
 }finally{await browser.close();await g.close();await rm(runtime,{recursive:true,force:true});}
});

test('real native form survives path/maximize/history; tab deep links wait for gesture; foreign links stay unavailable',{timeout:45000},async()=>{
 const fixture=createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><label>Private synthetic note<textarea></textarea></label>');});await new Promise(r=>fixture.listen(0,'localhost',r));
 const runtime=await mkdtemp(ROOT+'.test-desktop-links-'),g=await createGateway({port:0,runtime}),browser=await chromium.launch({headless:true,chromiumSandbox:true}),page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});page.setDefaultTimeout(4000);const button=name=>page.getByRole('button',{name,exact:true});
 try{await browserLogin(page,g.origin,runtime);const auth=await authenticate(g.origin,runtime),api=client(g.origin,auth),url=`http://localhost:${fixture.address().port}/`;
  for(const [label,openMode] of [['Synthetic frame','window'],['Synthetic tab','tab']]){const r=await api('/admin/apps','POST',{kind:'web',label,address:url,mode:'native',openMode,icon:'globe',allowedOrigins:[],userIds:[]});assert.equal(r.status,200);}
  await page.reload();await button('Open Synthetic frame').click();const frame=page.frameLocator('iframe[title="Synthetic frame"]');await frame.getByLabel('Private synthetic note').fill('Retained private synthetic text');await button('Maximize Synthetic frame').click();await expect(page).toHaveURL(/view=maximized/);await mkdir(ROOT+'screenshots',{recursive:true});await page.screenshot({path:ROOT+'screenshots/desktop-maximized.png'});await button('Restore size Synthetic frame').click();await page.goBack();await expect(button('Restore size Synthetic frame')).toBeVisible();await page.goForward();await expect(button('Maximize Synthetic frame')).toBeVisible();await expect(frame.getByLabel('Private synthetic note')).toHaveValue('Retained private synthetic text');
  await page.getByRole('link',{name:'Desktop',exact:true}).click();await expect(frame.getByLabel('Private synthetic note')).toHaveValue('Retained private synthetic text');await button('Close Synthetic frame').click();
  const tree=await(await api('/desktop')).json(),tab=tree.items.find(i=>i.label==='Synthetic tab');const tabURL=g.origin+'/desktop?app=old-name--'+tab.key+'&view=maximized';let popups=0;page.context().on('page',()=>popups++);await page.goto(tabURL);await expect(button('Open Synthetic tab in new tab ↗')).toBeVisible();await expect(page).not.toHaveURL(/view=maximized/);assert.equal(popups,0);const popupPromise=page.context().waitForEvent('page');await button('Open Synthetic tab in new tab ↗').click();const popup=await popupPromise;await expect(popup.getByLabel('Private synthetic note')).toBeVisible();await popup.close();
  const r=await api('/admin/users','POST',{username:'separate',password,role:'user',grants:['parcels']});assert.equal(r.status,200);await button('Navigation').click();await button('Sign out').click();await page.goto(tabURL);await page.getByLabel('username',{exact:true}).fill('separate');await page.getByLabel('password',{exact:true}).fill(password);await button('Enter →').click();await expect(page.getByText('This location is unavailable.',{exact:true})).toBeVisible();await expect(page.getByText('Synthetic tab',{exact:true})).toHaveCount(0);await expect(page.locator('iframe')).toHaveCount(0);
 }finally{await browser.close();await g.close();await rm(runtime,{recursive:true,force:true});await new Promise(r=>fixture.close(r));}
});
