import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {createGateway,ROOT} from '../../server/gateway.mjs';
import {browserLogin,password} from '../auth-helper.mjs';

test('personal desktop: real folders, appearance, private routes, drag, persisted maximize and frame continuity',{timeout:90000},async()=>{
 const runtime=await mkdtemp(ROOT+'.test-desktop-ui-'),g=await createGateway({port:0,runtime}),browser=await chromium.launch({headless:true,chromiumSandbox:true}),page=await browser.newPage({viewport:{width:1200,height:850},reducedMotion:'reduce'});page.setDefaultTimeout(4000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const button=name=>page.getByRole('button',{name,exact:true});
 const create=async name=>{await page.locator('.desktop-grid').click({button:'right',position:{x:500,y:300}});await page.getByRole('menuitem',{name:'New folder',exact:true}).click();await page.getByLabel('Folder name',{exact:true}).fill(name);await button('Create folder').click();await expect(button('Open '+name)).toBeVisible();};
 try{
  await browserLogin(page,g.origin,runtime);await expect(button('Open Parcels')).toBeVisible();
  await create('Projects');await button('Open Projects').click();await expect(page).toHaveURL(/\/desktop\/projects--[a-f0-9]{8}$/);await create('Sketches');const parentURL=page.url();await button('Open Sketches').click();const nestedURL=page.url();await expect(page.getByRole('link',{name:'Projects',exact:true})).toBeVisible();await page.getByRole('link',{name:'Desktop',exact:true}).click();
  await button('Open Parcels').click({button:'right'});await page.getByRole('menuitem',{name:'Rename',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Parcel desk');await button('Save').click();await expect(button('Open Parcel desk')).toBeVisible();
  await button('Open Parcel desk').click({button:'right'});await page.getByRole('menuitem',{name:'Change icon',exact:true}).click();await button('Icon star').click();await button('Save icon').click();await expect(button('Open Parcel desk').locator('svg')).toHaveAttribute('data-icon','star');
  await button('Open Parcel desk').focus();await page.keyboard.press('Shift+F10');await page.getByRole('menuitem',{name:'Change icon',exact:true}).click();await mkdir(ROOT+'screenshots',{recursive:true});await page.screenshot({path:ROOT+'screenshots/desktop-icon-gallery.png'});
  const png=await page.locator('.icon-grid').screenshot();await page.getByLabel('Upload icon').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:png});await button('Save icon').click();await expect(button('Open Parcel desk').locator('img')).toBeVisible();
  const uploadedURL=await button('Open Parcel desk').locator('img').getAttribute('src');await button('Open Parcel desk').click({button:'right'});await page.getByRole('menuitem',{name:'Change icon',exact:true}).click();await expect(page.getByRole('img',{name:'Current icon preview'})).toHaveAttribute('src',uploadedURL);await button('Save icon').click();await expect(button('Open Parcel desk').locator('img')).toHaveAttribute('src',uploadedURL);
  const app=await button('Open Parcel desk').boundingBox(),folder=await button('Open Projects').boundingBox();await page.mouse.move(app.x+40,app.y+30);await page.mouse.down();await page.mouse.move(folder.x+40,folder.y+30,{steps:12});await page.mouse.up();await expect(button('Open Parcel desk')).toHaveCount(0);
  await button('Open Projects').click();await expect(button('Open Parcel desk')).toBeVisible();await page.screenshot({path:ROOT+'screenshots/desktop-folders-path.png'});await button('Open Parcel desk').click();const win=page.locator('[data-app="parcels"]');await expect(win).toBeVisible();await win.locator('iframe').evaluate(el=>el.dataset.continuity='yes');const normal=await win.boundingBox();await button('Maximize Parcel desk').click();await expect(page).toHaveURL(/view=maximized/);await expect(win.locator('iframe')).toHaveAttribute('data-continuity','yes');await page.screenshot({path:ROOT+'screenshots/desktop-maximize-geometry.png'});
  await button('Restore size Parcel desk').click();await expect(page).not.toHaveURL(/view=maximized/);const restored=await win.boundingBox();assert.equal(restored.width,normal.width);assert.equal(restored.height,normal.height);await page.goBack();await expect(button('Restore size Parcel desk')).toBeVisible();await page.goForward();await expect(button('Maximize Parcel desk')).toBeVisible();
  await page.getByRole('link',{name:'Desktop',exact:true}).click();await expect(win.locator('iframe')).toHaveAttribute('data-continuity','yes');await button('Close Parcel desk').click();await page.goto(nestedURL);await expect(page.getByRole('link',{name:'Sketches',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('link',{name:'Sketches',exact:true})).toBeVisible();
  await page.goto(parentURL);await expect(button('Open Parcel desk').locator('img')).toBeVisible();await button('Open Sketches').click({button:'right'});await page.screenshot({path:ROOT+'screenshots/desktop-context-menu.png'});await page.keyboard.press('Escape');await expect(button('Open Sketches')).toBeFocused();
  await page.setViewportSize({width:390,height:844});await button('Navigation').click();await button('New folder').click();await page.getByLabel('Folder name',{exact:true}).fill('Touch folder');await button('Create folder').click();await expect(button('Open Touch folder')).toBeVisible();await page.screenshot({path:ROOT+'screenshots/desktop-narrow.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await button('Navigation').click();await button('Sign out').click();assert.equal(page.url(),parentURL);await page.reload();await page.getByLabel('username',{exact:true}).fill('admin');await page.getByLabel('password',{exact:true}).fill(password);await button('Enter →').click();await expect(button('Open Parcel desk')).toBeVisible();assert.equal(page.url(),parentURL);
  await page.goto(g.origin+'/desktop/not-yours--deadbeef?app=private--badc0ffe&view=maximized');await expect(page.getByText('This location is unavailable.',{exact:true})).toBeVisible();await expect(page.locator('.shortcut')).toHaveCount(0);assert.deepEqual(errors,[]);
 }finally{await browser.close();await g.close();await rm(runtime,{recursive:true,force:true});}
});
