import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import http from 'node:http';
import {createGateway,ROOT} from '../../server/gateway.mjs';
import {browserLogin,authenticate,client,password} from '../auth-helper.mjs';
test('real five-step web app wizard, native tab/frame, streamed preview, grants and status preference',{timeout:120000},async()=>{
 const fixture=http.createServer((req,res)=>{if(req.url!=='/nocors')res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Fixture app</title><h1>Synthetic web app</h1><textarea aria-label="Fixture text" style="width:400px;height:200px"></textarea>');});await new Promise(r=>fixture.listen(0,'localhost',r));
 const address=`http://localhost:${fixture.address().port}/`;
 const runtime=await mkdtemp(tmpdir()+'/relay-webapps-ui-');let g=await createGateway({port:0,runtime});const browser=await chromium.launch({headless:true,chromiumSandbox:true});const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const button=name=>page.getByRole('button',{name,exact:true});
 async function panel(){await button('Navigation').click();await button('Control Panel').click();await page.getByRole('tab',{name:'Apps',exact:true}).click();}
 async function draft(mode,label){await button('Add app').click();await page.getByLabel(mode,{exact:true}).check();await button('Next').click();await page.getByLabel('App name',{exact:true}).fill(label);await page.getByLabel('Address',{exact:true}).fill(address);await button('Next').click();}
 try{
  await mkdir(ROOT+'screenshots',{recursive:true});await browserLogin(page,g.origin,runtime);
  await button('Open Parcels').focus();await expect(page.locator('#health-parcels .health-detail')).toContainText('Relay');
  assert.equal(await page.locator('#health-parcels .health-detail').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),true,'Focused health tooltip must not be clipped by shortcut scrolling');
  const admin=await authenticate(g.origin,runtime),api=client(g.origin,admin);
  const alice=await(await api('/admin/users','POST',{username:'alice',password,role:'user',grants:[]})).json();
  const disabled=await(await api('/admin/users','POST',{username:'disabled',password,role:'user',grants:[]})).json();await api('/admin/users/'+disabled.id,'PATCH',{disabled:true});
  await panel();
  await button('Add app').click();await expect(page.getByText('Step 1 of 5')).toBeVisible();await button('Next').click();await page.getByLabel('App name',{exact:true}).fill('Draft');await page.getByLabel('Address',{exact:true}).fill('127.0.0.1:8080');await button('Next').click();await expect(page.getByRole('alert')).toContainText('http');await button('Back').click();await button('Next').click();await expect(page.getByLabel('App name',{exact:true})).toHaveValue('Draft');await button('Cancel').click();await expect(button('Edit app Draft')).toHaveCount(0);
  await draft('Native','CORS check');await button('Back').click();await page.getByLabel('Address',{exact:true}).fill(address+'nocors');await button('Next').click();await button('Test connection').click();await expect(page.getByRole('status').filter({hasText:'Reachable from Relay'})).toBeVisible();await expect(page.getByRole('status').filter({hasText:'Device check blocked or unavailable'})).toContainText('Unknown');await button('Back').click();await page.getByLabel('Address',{exact:true}).fill(address);await button('Next').click();await expect(page.locator('.app-wizard [role=status]')).toHaveCount(0);await button('Cancel').click();
  await draft('Streamed','Denied draft');await button('Back').click();await page.getByLabel('Address',{exact:true}).fill(g.origin);await button('Next').click();await button('Preview').click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('img',{name:'Streamed preview'})).toHaveCount(0);await button('Next').click();await button('Next').click();await button('Save app').click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('heading',{name:'Review app'})).toBeVisible();await button('Cancel').click();
  await draft('Native','Fixture tab');await page.getByLabel('New tab',{exact:true}).check();await button('Test connection').click();await expect(page.getByRole('status').filter({hasText:'Reachable from this device'})).toBeVisible();await page.screenshot({path:ROOT+'screenshots/webapps-wizard.png'});await button('Next').click();await button('Next').click();await expect(page.getByRole('heading',{name:'Review app'})).toBeVisible();await button('Save app').click();await expect(button('Edit app Fixture tab')).toBeVisible();await page.screenshot({path:ROOT+'screenshots/webapps-apps.png'});await button('Close settings').click();
  const popupPromise=page.context().waitForEvent('page');await button('Open Fixture tab').click();const popup=await popupPromise;await popup.waitForLoadState();await expect(popup.getByRole('heading',{name:'Synthetic web app'})).toBeVisible();assert.equal(await popup.evaluate(()=>window.opener),null);await popup.close();
  await panel();await draft('Native','Fixture frame');await button('Preview').click();await expect(page.frameLocator('iframe[title="Native preview"]').getByRole('heading',{name:'Synthetic web app'})).toBeVisible();await button('Next').click();await button('Next').click();await button('Save app').click();await expect(button('Edit app Fixture frame')).toBeVisible();await button('Close settings').click();await button('Open Fixture frame').click();await expect(page.frameLocator('iframe[title="Fixture frame"]').getByRole('heading',{name:'Synthetic web app'})).toBeVisible();await button('Close Fixture frame').click();
  await panel();await draft('Streamed','Fixture stream');await button('Preview').click();await expect(page.getByRole('img',{name:'Streamed preview'})).toBeVisible({timeout:20000});assert.ok(await page.getByRole('img',{name:'Streamed preview'}).evaluate(el=>el.naturalWidth>0));await page.screenshot({path:ROOT+'screenshots/webapps-stream-preview.png'});await button('Next').click();await page.getByLabel('Allow alice',{exact:true}).check();await expect(page.getByLabel('Allow disabled',{exact:true})).toHaveCount(0);await expect(page.getByLabel('Allow admin',{exact:true})).toHaveCount(0);await button('Next').click();await button('Save app').click();await expect(button('Edit app Fixture stream')).toBeVisible();await button('Close settings').click();await button('Open Fixture stream').click();await expect(page.locator('.stream-status')).toContainText('live',{timeout:20000});
  const entries=await(await api('/admin/apps')).json(),stream=entries.find(a=>a.label==='Fixture stream');
  await expect(page.getByLabel('Fixture stream streamed image')).not.toHaveClass(/awaiting/);
  await page.getByLabel('Fixture stream remote input').click({position:{x:80,y:100}});
  await expect.poll(()=>g.manager.resources.get(stream.id)?.page.evaluate(()=>document.activeElement?.tagName)).toBe('TEXTAREA');
  await page.keyboard.type('Actual streamed input');
  await expect.poll(()=>g.manager.resources.get(stream.id)?.page.locator('textarea').inputValue()).toBe('Actual streamed input');
  await page.screenshot({path:ROOT+'screenshots/webapps-stream.png'});await button('Close Fixture stream').click();
  const userAuth=await authenticate(g.origin,runtime,'alice'),userApi=client(g.origin,userAuth);const granted=await(await userApi('/session')).json();assert.deepEqual(granted.apps.map(a=>a.id),[stream.id]);assert.equal(granted.apps[0].address,undefined);assert.equal(granted.apps[0].url,undefined);
  const userContext=await browser.newContext();const [cookieName,cookieValue]=userAuth.cookie.split('=');await userContext.addCookies([{name:cookieName,value:cookieValue,url:g.origin}]);const userPage=await userContext.newPage();await userPage.goto(g.origin);await expect(userPage.getByRole('button',{name:'Open Fixture stream',exact:true})).toBeVisible();await expect(userPage.getByRole('button',{name:'Open Fixture tab',exact:true})).toHaveCount(0);await userContext.close();
  await button('Navigation').click();await button('Profile settings').click();await page.getByLabel('Show app status').uncheck();await expect(page.getByRole('status')).toContainText('Status preference saved');await page.screenshot({path:ROOT+'screenshots/webapps-profile.png'});await button('Close settings').click();await expect(page.locator('.health')).toHaveCount(0);await page.reload();await expect(button('Open Fixture tab')).toBeVisible();await expect(page.locator('.health')).toHaveCount(0);
  assert.equal((await(await api('/session')).json()).user.preferences.showAppStatus,false,'Preference visible to another existing session');
  assert.equal((await(await userApi('/session')).json()).user.preferences.showAppStatus,true,'Preference is per user');
  const hiddenRequests=[];const record=r=>{if(r.url().startsWith(address)||r.url().endsWith('/api/status'))hiddenRequests.push(r.url());};page.on('request',record);await page.waitForTimeout(5500);page.off('request',record);assert.deepEqual(hiddenRequests,[],'Hidden status does not poll health or probe device');
  await panel();await button('Edit app Fixture frame').click();await expect(page.getByRole('combobox',{name:'Icon',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Icon',exact:true}).selectOption('folder');await page.getByRole('combobox',{name:'Open in',exact:true}).selectOption('tab');await button('Save app').click();await expect(button('Edit app Fixture frame')).toBeVisible();const edited=(await(await api('/admin/apps')).json()).find(a=>a.label==='Fixture frame');assert.equal(edited.kind,'web');assert.equal(edited.icon,'folder');assert.equal(edited.openMode,'tab');
  await page.setViewportSize({width:320,height:700});await button('Add app').click();await button('Next').click();await page.getByLabel('App name',{exact:true}).fill('Retained draft');await page.getByRole('tab',{name:'Users',exact:true}).click();await page.getByRole('tab',{name:'Apps',exact:true}).click();await expect(page.getByLabel('App name',{exact:true})).toHaveValue('Retained draft');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:ROOT+'screenshots/webapps-wizard-narrow.png'});await button('Next').scrollIntoViewIfNeeded();await expect(button('Next')).toBeVisible();assert.deepEqual(errors,[]);
  await g.close();g=await createGateway({port:0,runtime});await page.setViewportSize({width:1280,height:900});await browserLogin(page,g.origin,runtime);await expect(button('Open Fixture tab')).toBeVisible();await expect(page.locator('.health')).toHaveCount(0);await button('Navigation').click();await button('Profile settings').click();await expect(page.getByLabel('Show app status')).not.toBeChecked();assert.deepEqual(errors,[]);
 }finally{await browser.close();await g.close();await new Promise(r=>fixture.close(r));await rm(runtime,{recursive:true,force:true});}
});
