import {browserLogin} from '../auth-helper.mjs';
import {createGateway, ROOT} from '../../server/gateway.mjs';
import {chromium, expect} from '@playwright/test';
import {mkdtemp, readFile, mkdir, rm} from 'node:fs/promises';
import path from 'node:path';
import net from 'node:net';
import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
const runtime=await mkdtemp(path.join(ROOT,'.test-integration-'));
const temporary=net.createServer();await new Promise(r=>temporary.listen(0,'127.0.0.1',r));const kp=temporary.address().port;await new Promise(r=>temporary.close(r));
const g=await createGateway({port:0,native:true,keepsakesPort:kp,runtime,data:path.join(runtime,'library')});
const browser=await chromium.launch({headless:true,chromiumSandbox:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const requests=[];page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
await mkdir(path.join(ROOT,'screenshots'),{recursive:true});
try{
 await browserLogin(page,g.origin,runtime);
 await expect(page).toHaveTitle('Private desktop');
 await expect(page.locator('body')).not.toContainText(/relay|after wicked/i);
 await expect(page.locator('footer .maker')).toHaveText('Made by Wicked Evil Incorporated');
 await expect(page.locator('.desktop-signature')).toHaveCount(0);
 const locked=await fetch(g.origin);
 assert.equal(locked.status,200);assert.equal((await fetch(g.origin+'/api/session')).status,401);
 await expect(page.getByRole('button',{name:'Open Parcels',exact:true})).toBeVisible();
 await page.screenshot({path:path.join(ROOT,'screenshots/desktop.png')});
 await page.getByRole('button',{name:'Open Parcels',exact:true}).click();
 await page.getByRole('button',{name:'Maximize Parcels',exact:true}).click();
 const parcel=page.frameLocator('iframe[title="Parcels"]');
 const payload=randomBytes(512*1024);
 await parcel.locator('#files').setInputFiles({name:'example.bin',mimeType:'application/octet-stream',buffer:payload});
 await parcel.locator('#note').fill('A synthetic transfer from your desktop.');
 await parcel.locator('#seal').click();
 await expect(parcel.locator('#download')).toBeVisible({timeout:15000});
 const waitDownload=page.waitForEvent('download');await parcel.locator('#download').click();const download=await waitDownload;
 const zipPath=await download.path();
 const hash=execFileSync('python3',['-c','import sys,zipfile,hashlib; z=zipfile.ZipFile(sys.argv[1]); print(hashlib.sha256(z.read("files/example.bin")).hexdigest()); assert "synthetic transfer" in z.read("README.md").decode()',zipPath],{encoding:'utf8'}).trim();
 assert.equal(hash,createHash('sha256').update(payload).digest('hex'));
 await page.screenshot({path:path.join(ROOT,'screenshots/native-parcels.png')});
 await page.getByRole('button',{name:'Minimize Parcels',exact:true}).click();
 await page.getByRole('button',{name:'Open Keepsakes',exact:true}).click();
 await page.getByRole('button',{name:'Maximize Keepsakes',exact:true}).click();
 const keeps=page.frameLocator('iframe[title="Keepsakes"]');
 await keeps.getByRole('button',{name:'Add clipping',exact:true}).click();

 // Use the project's original, labeled synthetic artwork rather than private media.
 const fixture=await readFile(path.join(ROOT,'tests/integration/synthetic-relay.png'));
 await keeps.getByLabel('Image file').setInputFiles({name:'synthetic-relay.png',mimeType:'image/png',buffer:fixture});
 await keeps.locator('#upload').getByLabel('Title',{exact:true}).fill('Demo reference');
 await keeps.locator('#upload input[name="creator"]').fill('Generated test fixture');
 await keeps.getByRole('button',{name:'Save clipping',exact:true}).click();
 await keeps.getByRole('button',{name:'Open Demo reference'}).click();
 await keeps.getByLabel('Notes',{exact:true}).fill('Saved from your browser. A little reference worth keeping.');
 await keeps.getByRole('button',{name:'Save changes'}).click();
 await expect(keeps.locator('#detail-status')).toContainText('Saved');
 await page.screenshot({path:path.join(ROOT,'screenshots/native-keepsakes.png')});
 await keeps.getByRole('button',{name:'Close clipping'}).click();
 await page.getByRole('button',{name:'Minimize Keepsakes',exact:true}).click();
 await page.getByRole('button',{name:'Open Notes Lab',exact:true}).click();
 await page.getByRole('button',{name:'Navigation',exact:true}).click();
 await page.locator('.quick-nav').getByRole('button',{name:/Signal Lab/}).click();
 const session=await page.evaluate(async()=>await(await fetch('/api/session')).json());
 async function patch(id,data){await page.evaluate(async({id,data,csrf})=>{const r=await fetch('/api/windows/'+id,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});if(!r.ok)throw Error('layout patch failed');},{id,data,csrf:session.csrf});}
 await patch('notes-lab',{x:150,y:60,width:570,height:430,visible:true,focused:true});
 await patch('signal-lab',{x:740,y:190,width:570,height:430,visible:true,focused:false});
 await page.reload();
 const surface=page.locator('[data-app="notes-lab"]').getByLabel('Notes Lab remote input');
 await expect(surface).toBeVisible();
 await expect(page.locator('[data-app="notes-lab"] .stream-status')).toContainText('live',{timeout:15000});
 await expect(page.locator('[data-app="signal-lab"] .stream-status')).toContainText('live',{timeout:15000});
 await surface.click({position:{x:80,y:150}});await page.keyboard.type('Hello from your desktop.');
 await expect.poll(async()=>g.manager.resources.get('notes-lab').page.locator('textarea').inputValue()).toBe('Hello from your desktop.');
 assert.equal(await g.manager.resources.get('signal-lab').page.locator('textarea').inputValue(),'');
 const beforeMove={...g.manager.windows.get('notes-lab')};
 const bar=await page.locator('[data-app="notes-lab"] .titlebar').boundingBox();
 await page.mouse.move(bar.x+90,bar.y+9);await page.mouse.down();await page.mouse.move(bar.x+114,bar.y+25,{steps:4});await page.mouse.up();
 await expect.poll(()=>g.manager.windows.get('notes-lab').x).toBe(beforeMove.x+24);
 const resize=await page.getByRole('button',{name:'Resize Notes Lab',exact:true}).boundingBox();
 await page.mouse.move(resize.x+resize.width/2,resize.y+resize.height/2);await page.mouse.down();await page.mouse.move(resize.x+resize.width/2+30,resize.y+resize.height/2+20,{steps:4});await page.mouse.up();
 await expect.poll(()=>g.manager.windows.get('notes-lab').width).toBe(beforeMove.width+30);
 await page.waitForTimeout(300);await page.screenshot({path:path.join(ROOT,'screenshots/two-streams.png')});
 await page.getByRole('button',{name:'Minimize Notes Lab',exact:true}).click();
 await expect.poll(async()=>(await g.manager.metrics()).windows.find(w=>w.id==='notes-lab').capturing).toBe(false);
 await page.getByRole('button',{name:'Restore Notes Lab',exact:true}).click();
 await expect.poll(async()=>g.manager.resources.get('notes-lab').page.locator('textarea').inputValue()).toBe('Hello from your desktop.');
 await page.reload();await expect(page.locator('[data-app="notes-lab"] .stream-status')).toContainText('live',{timeout:15000});
 assert.equal(await g.manager.resources.get('notes-lab').page.locator('textarea').inputValue(),'Hello from your desktop.');
 assert.ok(requests.every(url=>new URL(url).origin===g.origin),'Only gateway HTTP connections');
 assert.deepEqual(errors,[]);
 await patch('signal-lab',{visible:false,focused:false});
 await patch('keepsakes',{x:70,y:35,width:720,height:700,visible:true,focused:false});
 await patch('notes-lab',{x:830,y:195,width:480,height:460,visible:true,focused:true});
 // Exercise restored layout before a delayed initial ResizeObserver notification.
 await page.addInitScript(()=>{const Observer=window.ResizeObserver;window.ResizeObserver=class extends Observer{observe(...args){setTimeout(()=>super.observe(...args),500);}};});
 await page.reload();
 await page.frameLocator('iframe[title="Keepsakes"]').getByRole('button',{name:'Open Demo reference'}).click();
 await page.waitForTimeout(700);
 await expect.poll(()=>g.manager.windows.get('notes-lab').x).toBe(830);
 await expect(page.locator('[data-app="notes-lab"] .stream-status')).toContainText('live',{timeout:15000});
 await page.screenshot({path:path.join(ROOT,'screenshots/hybrid-desktop.png')});
 console.log('PASS real Svelte+gateway: native 512KiB ZIP exact bytes, native Keepsakes upload/notes, two independent streamed pages, input isolation, capture pause/resume, reconnect retention, same-origin requests, no page exceptions.');
}finally{await browser.close();await g.close();await rm(runtime,{recursive:true,force:true});}
