<script>
 import {tick,onMount} from 'svelte';
 import Icon from './Icon.svelte';
 import {reveal} from './motion.js';
 import {ancestry,folderPath,slotPosition,slotAt,CELL_HEIGHT,CELL_WIDTH} from './desktop.js';
 let {state:desktopState,folderId,areaHeight,motion,apps,showStatus,observation,statusLabel,statusDetail,onopen,onmutate,onupload,onerror,busy='',unavailable=false}=$props();
 let grid,menuNode=$state(),dialogNode=$state(),menu=$state(null),editor=$state(null),name=$state(''),destination=$state(''),chosen=$state(null),file=$state(null),preview=$state(''),saving=$state(false),message=$state(''),gesture=$state(null),suppressClick=false,returnFocus;
 let rows=$derived(Math.max(1,Math.floor((areaHeight-30)/CELL_HEIGHT)));
 let visible=$derived(desktopState.items.filter(i=>i.parentId===folderId));
 let maxSlot=$derived(Math.max(0,...visible.map(i=>i.slot)));
 let folders=$derived(desktopState.items.filter(i=>i.kind==='folder'&&i.id!==editor?.item?.id&&!ancestry(desktopState.items,i.id)?.some(p=>p.id===editor?.item?.id)));
 async function showMenu(e,item=null){e.preventDefault();e.stopPropagation();returnFocus=e.target.closest('button')||grid;const b=returnFocus.getBoundingClientRect();menu={item,x:e.type==='keydown'?b.x:e.clientX,y:e.type==='keydown'?b.bottom:e.clientY};await tick();const r=menuNode.getBoundingClientRect();menu={...menu,x:Math.max(4,Math.min(menu.x,innerWidth-r.width-8)),y:Math.max(4,Math.min(menu.y,innerHeight-r.height-8))};menuNode.querySelector('button')?.focus();}
 function closeMenu(restore=true){menu=null;if(restore)returnFocus?.focus();}
 function menuKeys(e){const buttons=[...menuNode.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(e.key==='Escape'||e.key==='Tab'){e.preventDefault();closeMenu();}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}}
 async function edit(kind,item=null){closeMenu(false);editor={kind,item};name=item?.label||'';destination=item?.parentId||'';chosen=item?.icon?.type==='builtin'?item.icon.name:undefined;file=null;message='';clearPreview();await tick();dialogNode.showModal();dialogNode.querySelector('input,select,button')?.focus();}
 export function newFolder(){returnFocus=document.activeElement;void edit('create');}
 function clearPreview(){if(preview)URL.revokeObjectURL(preview);preview='';}
 function cancel(){if(saving)return;dialogNode?.close();editor=null;clearPreview();returnFocus?.focus();}
 async function submit(){if(saving)return;saving=true;message='';try{const {kind,item}=editor;if(kind==='create')await onmutate('/desktop/folders','POST',{parentId:folderId,label:name});else if(kind==='rename')await onmutate('/desktop/items/'+item.id,'PATCH',{label:name});else if(kind==='move')await onmutate('/desktop/items/'+item.id,'PATCH',{parentId:destination||null});else if(kind==='remove')await onmutate('/desktop/items/'+item.id,'DELETE');else if(kind==='icon'){if(file)await onupload(item.id,file);else if(chosen!==undefined)await onmutate('/desktop/items/'+item.id,'PATCH',{icon:chosen?{type:'builtin',name:chosen}:null});}saving=false;cancel();}catch(e){message=e.message;}finally{saving=false;}}
 function upload(e){message='';const value=e.target.files[0];if(!value)return;if(!['image/png','image/jpeg','image/webp'].includes(value.type)||value.size>1024*1024){message='Choose a PNG, JPEG or WebP image up to 1 MiB.';e.target.value='';return;}clearPreview();file=value;preview=URL.createObjectURL(value);}
 async function reset(item){closeMenu();try{await onmutate('/desktop/items/'+item.id,'PATCH',{label:null,icon:null});}catch(e){onerror(e.message);}}
 function start(e,item){if(e.button!==0)return;gesture={id:item.id,x:e.clientX,y:e.clientY,active:false};e.currentTarget.setPointerCapture(e.pointerId);}
 function drag(e){if(!gesture)return;if(Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>7){gesture={...gesture,active:true};}}
 async function drop(e){if(!gesture)return;const g=gesture;gesture=null;if(!g.active)return;suppressClick=true;setTimeout(()=>suppressClick=false,0);const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-item-id]');const folder=desktopState.items.find(i=>i.id===target?.dataset.itemId&&i.kind==='folder'&&i.id!==g.id);const rect=grid.getBoundingClientRect();try{await onmutate('/desktop/items/'+g.id,'PATCH',folder?{parentId:folder.id}:{slot:slotAt(e.clientX-rect.x+grid.scrollLeft-CELL_WIDTH/2,e.clientY-rect.y+grid.scrollTop-45,rows)});}catch(e){onerror(e.message);}}
 onMount(()=>{const outside=e=>{if(menu&&!menuNode?.contains(e.target))closeMenu(false);};window.addEventListener('pointerdown',outside);return()=>{window.removeEventListener('pointerdown',outside);clearPreview();};});
</script>
<!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_no_noninteractive_element_interactions -->
<section class="desktop-grid" bind:this={grid} tabindex="0" aria-label="Desktop items" oncontextmenu={e=>showMenu(e)} onkeydown={e=>{if(e.target===grid&&(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')))showMenu(e);}}>
 {#if unavailable}<div class="desktop-unavailable"><p>This location is unavailable.</p><a href="/desktop" onclick={e=>{if(!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey&&e.button===0){e.preventDefault();onopen(null);}}}>Return to Desktop</a></div>
 {:else}<div class="grid-extent" style:width={Math.max(1,Math.floor(maxSlot/rows)+1)*CELL_WIDTH+36+'px'} style:height={rows*CELL_HEIGHT+24+'px'}></div>
 {#each visible as item,i (item.id)}
 {@const pos=slotPosition(item.slot,rows)}{@const app=apps.find(a=>a.id===item.appId)}
 <button class="shortcut desktop-shortcut" class:dragging={gesture?.id===item.id&&gesture?.active} data-item-id={item.id} style:left={pos.x+'px'} style:top={pos.y+'px'} use:reveal={{enabled:motion,delay:Math.min(i,6)*25,kind:'slide'}} aria-label={'Open '+item.label} aria-describedby={app&&showStatus?'health-'+app.id:undefined} disabled={busy===item.appId} onclick={()=>{if(!suppressClick)onopen(item);}} oncontextmenu={e=>showMenu(e,item)} onkeydown={e=>{if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10'))showMenu(e,item);}} onpointerdown={e=>start(e,item)} onpointermove={drag} onpointerup={drop} onpointercancel={()=>gesture=null} title={app&&showStatus?statusDetail(observation(app)):item.label}>
 {#if item.icon?.type==='upload'}<img src={item.icon.url} alt="" draggable="false"/>{:else}<Icon name={item.icon?.name||'folder'}/>{/if}<span>{item.label}</span><small>{item.kind==='folder'?'folder':app?.mode==='gateway'?'gateway · experimental':app?.mode==='stream'?'streamed':app?.openMode==='tab'?'native · new tab':'native'}</small>
 {#if app&&showStatus}<small id={'health-'+app.id} class="health"><i class:online={observation(app)?.state==='Online'} class:offline={observation(app)?.state==='Offline'}></i>{statusLabel(observation(app))}<span class="health-detail">{statusDetail(observation(app))}</span></small>{/if}
 </button><button class="item-actions" aria-label={'Actions for '+item.label} style:left={pos.x+76+'px'} style:top={pos.y+'px'} onclick={e=>showMenu(e,item)}>⋯</button>{/each}{/if}
</section>
{#if menu}
 <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
 <div class="desktop-context" role="menu" tabindex="-1" aria-label="Desktop actions" bind:this={menuNode} style:left={menu.x+'px'} style:top={menu.y+'px'} onkeydown={menuKeys}>
 {#if menu.item}{@const item=menu.item}<button role="menuitem" onclick={()=>{closeMenu();onopen(item);}}>Open</button><button role="menuitem" onclick={()=>edit('rename',item)}>Rename</button><button role="menuitem" onclick={()=>edit('icon',item)}>Change icon</button><button role="menuitem" onclick={()=>edit('move',item)}>Move to…</button>{#if item.kind==='folder'}<button role="menuitem" onclick={()=>edit('remove',item)}>Remove folder</button>{:else}<button role="menuitem" onclick={()=>reset(item)}>Reset appearance</button>{/if}{:else}<button role="menuitem" onclick={()=>edit('create')}>New folder</button>{/if}
 </div>{/if}
{#if editor}
 <dialog class="desktop-dialog" bind:this={dialogNode} aria-label={editor.kind==='icon'?'Change icon':'Desktop item'} oncancel={e=>{e.preventDefault();cancel();}}>
 <form onsubmit={e=>{e.preventDefault();submit();}}><h2>{editor.kind==='create'?'New folder':editor.kind==='rename'?'Rename':editor.kind==='move'?'Move to…':editor.kind==='remove'?'Remove folder':'Change icon'}</h2>
 {#if editor.kind==='create'||editor.kind==='rename'}<label>{editor.kind==='create'?'Folder name':'Name'}<input bind:value={name} required maxlength="64"/></label>
 {:else if editor.kind==='move'}<label>Destination<select bind:value={destination}><option value="">Desktop</option>{#each folders as f}<option value={f.id}>{ancestry(desktopState.items,f.id)?.map(p=>p.label).join(' / ')}</option>{/each}</select></label>
 {:else if editor.kind==='remove'}<p>Remove “{editor.item.label}”? Contents move up one level. Apps and their data are not deleted.</p>
 {:else}<div class="icon-preview">{#if preview}<img src={preview} alt="Selected icon preview"/>{:else if chosen===undefined&&editor.item.icon?.type==='upload'}<img src={editor.item.icon.url} alt="Current icon preview"/>{:else}<Icon name={chosen||(editor.item.kind==='folder'?'folder':apps.find(a=>a.id===editor.item.appId)?.icon)||'globe'}/>{/if}</div><div class="icon-grid">{#each desktopState.iconChoices as choice}<button type="button" aria-label={'Icon '+choice} aria-pressed={!file&&chosen===choice} onclick={()=>{chosen=choice;file=null;clearPreview();}}><Icon name={choice}/><span>{choice}</span></button>{/each}</div><label>Upload icon<input type="file" accept="image/png,image/jpeg,image/webp" onchange={upload}/></label><p class="dialog-hint">PNG, JPEG or WebP · up to 1 MiB. Saved privately as a small PNG.</p>{#if editor.item.kind==='app'}<button type="button" onclick={()=>{chosen=null;file=null;clearPreview();}}>Use app default</button>{/if}{/if}
 {#if message}<p role="alert">{message}</p>{/if}<div class="dialog-actions"><button type="button" disabled={saving} onclick={cancel}>Cancel</button><button disabled={saving} type="submit">{saving?'Saving…':editor.kind==='create'?'Create folder':editor.kind==='icon'?'Save icon':editor.kind==='remove'?'Remove folder':'Save'}</button></div></form>
 </dialog>{/if}
<style>
 .item-actions{position:absolute;width:28px;height:28px;color:#a8a29e;background:#0c0a09}.item-actions:hover,.item-actions:focus-visible{color:#fafaf9;background:#292524}
 .desktop-grid{position:absolute;inset:0;overflow:auto;outline-offset:-2px}.grid-extent{pointer-events:none}.desktop-shortcut{position:absolute;width:100px;height:120px;gap:5px;touch-action:none;user-select:none}.desktop-shortcut>span{max-width:106px;overflow-wrap:anywhere;max-height:36px;overflow:hidden;font-size:12px}.desktop-shortcut img{width:43px;height:43px;object-fit:contain}.desktop-shortcut.dragging{opacity:.5;outline:1px dashed #a8a29e}.desktop-context{position:fixed;z-index:1800;min-width:175px;max-width:calc(100vw - 16px);padding:5px;background:#1c1917;border:1px solid #a8a29e;box-shadow:4px 4px #0008}.desktop-context button{display:block;text-align:left;width:100%;padding:10px 12px}.desktop-context button:hover,.desktop-context button:focus{background:#44403c;outline-offset:-2px}.desktop-dialog{width:min(540px,calc(100vw - 24px));max-height:calc(100dvh - 40px);overflow:auto;background:#1c1917;color:#fafaf9;border:1px solid #a8a29e;padding:22px;font:inherit}.desktop-dialog::backdrop{background:#0009}.desktop-dialog h2{font-size:16px;margin:0 0 20px}.desktop-dialog label{display:block;margin:12px 0}.desktop-dialog input,.desktop-dialog select{display:block;width:100%;background:#0c0a09;color:#fafaf9;border:1px solid #78716c;padding:10px;margin-top:8px;font:inherit}.desktop-dialog button{padding:9px 12px;border:1px solid #78716c}.dialog-actions{display:flex;justify-content:flex-end;gap:12px;margin-top:24px}.icon-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(78px,1fr));gap:8px}.icon-grid button{display:flex;flex-direction:column;align-items:center;gap:8px;padding:8px 2px;font-size:10px;overflow-wrap:anywhere}.icon-grid button[aria-pressed=true]{background:#44403c;border-color:#fafaf9}.icon-grid :global(svg){width:28px;height:28px}.icon-preview{height:64px;margin-bottom:16px}.icon-preview :global(svg),.icon-preview img{width:64px;height:64px;object-fit:contain}.dialog-hint{color:#a8a29e;font-size:11px}.desktop-unavailable{padding:30px}.desktop-unavailable a{color:inherit}
</style>
